#!/bin/bash
base_url="https://bytebytego.com/images/courses/system-design-interview/scale-from-zero-to-millions-of-users"

# Download all images
curl -L -o "figure-1-1-WCFZBBLA.png" "${base_url}/figure-1-1-WCFZBBLA.png"
curl -L -o "figure-1-2-GPY73ZNO.png" "${base_url}/figure-1-2-GPY73ZNO.png"
curl -L -o "figure-1-3-2P4MNG7C.png" "${base_url}/figure-1-3-2P4MNG7C.png"
curl -L -o "figure-1-4-2EGRRANZ.png" "${base_url}/figure-1-4-2EGRRANZ.png"
curl -L -o "figure-1-5-TJLQVE5N.svg" "${base_url}/figure-1-5-TJLQVE5N.svg"
curl -L -o "figure-1-6-L2YNDDKF.png" "${base_url}/figure-1-6-L2YNDDKF.png"
curl -L -o "figure-1-7-GGNXNZX6.svg" "${base_url}/figure-1-7-GGNXNZX6.svg"
curl -L -o "figure-1-8-AVKYQBAQ.png" "${base_url}/figure-1-8-AVKYQBAQ.png"
curl -L -o "figure-1-9-SA7OOP7O.svg" "${base_url}/figure-1-9-SA7OOP7O.svg"
curl -L -o "figure-1-10-E6HDAMPH.png" "${base_url}/figure-1-10-E6HDAMPH.png"
curl -L -o "figure-1-11-VI5Z74Q2.png" "${base_url}/figure-1-11-VI5Z74Q2.png"
curl -L -o "figure-1-12-WTWFBLWX.png" "${base_url}/figure-1-12-WTWFBLWX.png"
curl -L -o "figure-1-13-WILHQ2SA.png" "${base_url}/figure-1-13-WILHQ2SA.png"
curl -L -o "figure-1-14-CCBCQMO6.png" "${base_url}/figure-1-14-CCBCQMO6.png"
curl -L -o "figure-1-15-GICUI26J.png" "${base_url}/figure-1-15-GICUI26J.png"
curl -L -o "figure-1-16-DUWJTBCU.png" "${base_url}/figure-1-16-DUWJTBCU.png"
curl -L -o "figure-1-17-J2NLNRNY.svg" "${base_url}/figure-1-17-J2NLNRNY.svg"
curl -L -o "figure-1-18-P3WDK5LN.svg" "${base_url}/figure-1-18-P3WDK5LN.svg"
curl -L -o "figure-1-19-MOPDW7TD.png" "${base_url}/figure-1-19-MOPDW7TD.png"
curl -L -o "figure-1-20-VLGHMELC.svg" "${base_url}/figure-1-20-VLGHMELC.svg"
curl -L -o "figure-1-21-ZDWDWEO5.svg" "${base_url}/figure-1-21-ZDWDWEO5.svg"
curl -L -o "figure-1-22-FI2MHR5M.svg" "${base_url}/figure-1-22-FI2MHR5M.svg"
curl -L -o "figure-1-23-3IYFN6Q6.png" "${base_url}/figure-1-23-3IYFN6Q6.png"

echo "Download complete!"
