apiVersion: v1
kind: Pod
metadata:
    name: my-nginx-pod
    labels:
        app: nginx
        rel: stable
spec:
  containers:
    - name: my-nginx-container
      image: nginx:alpine
      ports:
        - containerPort: 80